name: CI/CD pipeline for BudgetService

on:
  pull_request:
    branches:
      - master
      - release/BudgetService/**
  push:
    branches:
      - release/BudgetService/**

jobs:
  build:
    uses: ./.github/workflows/service-build.yaml
    with:
      service-name: BudgetService

  release:
    needs: build
    uses: ./.github/workflows/service-release.yaml
    with:
      service-name: BudgetService
