name: CI/CD pipeline for Client

on:
  pull_request:
    branches:
      - master
      - release/Client/**
  push:
    branches:
      - release/Client/**

jobs:
  build:
    uses: ./.github/workflows/service-build.yaml
    with:
      service-name: Client

  release:
    needs: build
    uses: ./.github/workflows/service-release.yaml
    with:
      service-name: Client
