name: CI/CD pipeline for FinanceService

on:
  pull_request:
    branches:
      - master
      - release/FinanceService/**
  push:
    branches:
      - release/FinanceService/**

jobs:
  build:
    uses: ./.github/workflows/service-build.yaml
    with:
      service-name: FinanceService

  release:
    needs: build
    uses: ./.github/workflows/service-release.yaml
    with:
      service-name: FinanceService
