name: Build and test IdentityService

on:
  pull_request:
    branches:
      - master
      - release/identityservice*/**
    paths:
      - 'dev/identityservice/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./src/Saver.IdentityService

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Check for vulnerabilities
      run: |
        dotnet list package --vulnerable --include-transitive 2>&1 | tee build.log
        echo "Analyze dotnet list package command log output..."
        grep -q -i "critical\|high\|moderate\|low" build.log; [ $? -eq 0 ] && echo "Security Vulnerabilities found on the log output" && exit 1

    - name: Test
      working-directory: ./test/Saver.IdentityService.Tests
      run: dotnet test --no-build --verbosity normal
