name: CI/CD pipeline for PredictionsService

on:
  pull_request:
    branches:
      - master
      - release/PredictionsService/**
  push:
    branches:
      - release/PredictionsService/**

jobs:
  build:
    uses: ./.github/workflows/service-build.yaml
    with:
      service-name: PredictionsService

  release:
    needs: build
    uses: ./.github/workflows/service-release.yaml
    with:
      service-name: PredictionsService
