name: Build and test a microservice

on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, format('dev/{0}/', inputs.service-name)) || startsWith(github.event.pull_request.base.ref, format('release/{0}/', inputs.service-name)) }}

    defaults:
      run:
        working-directory: ./src/Saver.${{ inputs.service-name }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      working-directory: ./test/Saver.${{ inputs.service-name }}.Tests
      run: dotnet test --no-build --verbosity normal

